FROM debian:latest

WORKDIR /game

RUN apt update && \
    apt install -y git clang clang-13 llvm-13 make libxml2 cmake libwayland-dev libxkbcommon-dev xorg-dev

COPY . .

RUN ./scripts/build-deps.sh
RUN ./scripts/build-linux-release.sh

